name = "LMnews"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "517556cc-3f00-42b2-bcdb-d99cf9e71253"      # 替换为你创建的数据库 ID
